class Txn_Pool:
    def __init__(self):
        self.txn_map = {}
    
    def set_txn(self, txn):
        """
        Set a txn in the txn pool
        """
        self.txn_map[txn.id] = txn
    
    def existing_txn(self, address):
        """
        find a txn generated by an address in the txn pool
        """
        for txn in self.txn_map.values():
            if txn.input['address'] == address:
                return txn
    
    def txn_data(self):
        """
        return the txns from the txn pool represented in json serialized form
        """
        return(list(map(
            lambda txn: txn.to_json(),
            self.txn_map.values()
        )))
    
    def clear_txns(self, blockchain):
        for block in blockchain.chain:
            for txn in block.data['txns']:
                try:
                    del self.txn_map[txn['id']]
                except KeyError:
                    pass
